add festive cheer
ethanmoffat/arglonbot pull request #1
Opened 2024-11-12 19:41 UTC by MrDanOak

🫨🎄

2024-11-12 21:04 UTC, sorokya approved these changes
I approve

2024-11-13 07:14 UTC, ethanmoffat commented on arglonbot/Program.cs
>      var zoneInfo = TimeZoneInfo.FindSystemTimeZoneById("Pacific Standard Time");
Is zoneInfo used anymore?

2024-11-13 07:17 UTC, ethanmoffat commented on arglonbot/Program.cs
> +    { Month: 12, Day: 25 } => "Happy christmas 🎅🏻",
I'm both shocked and disturbed that the brits say "Happy christmas" and not "Merry Christmas"

Although the "night before christmas" traditional children's book I grew up with had "happy christmas" so I'll allow it

2024-11-13 08:23 UTC, Cirras requested changes

2024-11-13 08:23 UTC, Cirras commented on arglonbot/Program.cs
> +    { Month: 12, Day: 25 } => "Happy christmas 🎅🏻",
My friends, cast off the shackles of British oppression.
```suggestion
    { Month: 12, Day: 24 } now => "Merry christmas eve 🎅🏻",
    { Month: 12, Day: 25 } => "Merry christmas 🎅🏻",
```

2024-11-13 08:24 UTC, MrDanOak commented on arglonbot/Program.cs
>      var zoneInfo = TimeZoneInfo.FindSystemTimeZoneById("Pacific Standard Time");
good call, have removed :)

2024-11-13 12:23 UTC, Cirras approved these changes
🎅

2024-12-26 03:16 UTC, Cirras commented
@ethanmoffat grinch confirmed.

2025-01-08 18:58 UTC, merged